### ISSUE TITLE
parse into own or make a checklist

### ISSUE THREAD

**Issue by gseals** [gseals/MovieFriend#2]
- [ ] pull data through via axios
- [ ] routing

- [ ] plan out which button presses will do what and build those routes individually
- [ ] create SQL file that automatically builds database how Crystal/Ashley did

- [ ] media query to downsize cards to mobile
- [ ] make sure the plot info does not overflow from card

- [ ] can we utilize speech recognition function to put text in search bar?

- [ ] grab uid from firebase and put it into sql server to identify user because we want to only display an individual user per session based on uid. what if, instead of asking for first and last name, we grab that info from the google object?
- [ ] 
- [ ] we should be able to see upcoming events and old events. we can make events old by using a ternary testing to see if the date of the event is either ahead or behind the current date
- [ ] the events page will have old and upcoming events listed. however, the page will also have a button that says "Create an event. The create an event page will redirect to another page with a form that asks for date and time of event, location, notes, and asks who you want to invite (add another person button click option?)
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] from moviedatabase, we need to be able to click on movies and, based on the id of each, then send that info to populate the movieChoices table. one entry per invite?
- [ ] 
- [ ] utilize twilio to send out invitations via email
- [ ]
